### ISSUE TITLE
User should be able to save recorded video to their album

### ISSUE THREAD

**Issue by blurrah** [Team-Plofpigeon/vavio-application#22]
Just so they can keep the video they made on their phone to show it to others. Might even add the function for the Eboman'd video.

**Comment by jberghoef** [comment]
Can be set by uncommenting a part of the "processVideo" function in the CDVCapture.m file. This is a part of cordova-plugin-media-capture.

![schermafbeelding 2015-05-21 om 11 09 14](https://cloud.githubusercontent.com/assets/1595777/7745235/dd4950da-ffa9-11e4-9267-7baf535ebb22.png)

Gives a warning when compiling in Xcode in a seemingly unrelated VoiceOver component.

**Comment by jberghoef** [comment]
Gives a warning when compiling in Xcode in a seemingly unrelated VoiceOver component.

**Comment by blurrah** [comment]
Closed because of the video sharing functionality working, will uncomment that part when milestone 0.2.0 is done.
