### ISSUE TITLE
Add multiple challenge options

### ISSUE THREAD

**Issue by blurrah** [Team-Plofpigeon/vavio-application#3]
For the first prototype we should add in multiple challenge options so we can choose how the user gets challenges.

Three options:
- Pick 3 (picture/video/burst, action, with who)
- Roulette (randomly picked challenge)
- Predefined (predefined challenge)

**Comment by mitchellslager** [comment]
After testing the app the group decided to remove 1 of these 3 options.
"Pick 3" will not be implemented in the app. 

This leaves us with:
- Roulette (randomly picked challenge)
- Predefined (predefined challenge)

**Comment by blurrah** [comment]
Ok, closing!
