### ISSUE TITLE
Splash screen bug

### ISSUE THREAD

**Issue by mitchellslager** [Team-Plofpigeon/vavio-application#33]
When starting the app in the Xcode the splash screen takes a long time loading. It then fades out very slowly. This problem just came out of the blue.

I changed the splash screen to the vavio one and the app worked correctly for a few hours.

**Comment by blurrah** [comment]
Does it happen on your phone too without debugging with Xcode?

**Comment by mitchellslager** [comment]
No, on my phone the splash screen acts normal.

**Comment by blurrah** [comment]
Okay, putting it on hold for now.
