### ISSUE TITLE
Backlog milestone v0.1.0

### ISSUE THREAD

**Issue by blurrah** [Team-Plofpigeon/vavio-application#4]
Backlog milestone version 0.1.0

**Backend**:
- ~~Create route for creating custom user defined challenge~~
- ~~Store user defined challenges in a variable~~

**Frontend**:
- ~~Build support for deeplinking (custom URL scheme) (angular should react to listenerURL)~~
- ~~Edit predefined to be user defined challenge~~
- ~~Add share button to completed challenge page~~
- ~~Remove "Pick Three" challenge page~~
- ~~Remove test, ionic sample and unused code~~

**Comment by mitchellslager** [comment]
Added to Frontend:
- Remove "Pick Three" challenge page
- Remove test, ionic sample and unused code

**Comment by blurrah** [comment]
All items done.
